target_locations:
  Bhadla Solar Park:
    location:
      - 27.539669
      - 71.915253
    area: 57
    power: 2245
  Target 1:
    location:
      - 23.25991
      - 77.41261
    permanent: true
  Pavagada Solar Park:
    location:
      - 14.251944
      - 77.4475
    area: 53
    power: 2050
  Solar Power Plant Khera Silajit:
    location:
      - 25.835157
      - 79.65287
  Target 2:
    location:
      - 22.71961
      - 75.85771
    permanent: true
  54 MW PV SOLAR POWER PLANT:
    location:
      - 21.313376
      - 78.6013
    power: 54
  Solar Power Plant Chandasar:
    location:
      - 27.972365
      - 73.063411
  Kamuthi Solar Power Project:
    location:
      - 9.347568
      - 78.392162
    area: 10
    power: 648
  Charanka Solar Park:
    location:
      - 23.9
      - 71.2
    area: 20
    power: 615
  5MW Solar Power Plant Varroc:
    location:
      - 21.059537
      - 74.375055
    power: 5
  Rewa Ultra Mega Solar:
    location:
      - 24.480278
      - 81.574444
    area: 6.4
    power: 750
  BOSCH Solar Power Plant:
    location:
      - 15.981156
      - 74.998076
    area: 0.364
    power: 115
  Bitta Solar Power Plant:
    location:
      - 23.262778
      - 69.024167
    area: 1.4
    power: 40
  Indira Paryavaran Bhawan:
    location:
      - 28.585154
      - 77.218347
    area: 0.0046
    power: 0.93
  Kurnool Ultra Mega Solar Park:
    location:
      - 15.681522
      - 78.283749
    area: 24
    power: 1000
  Chennai Metropolitan Area:
    location:
      - 13.083667
      - 80.268667
  Mandsaur Solar Farm:
    location:
      - 24.088056
      - 75.799722
    area: 1.1435
    power: 250
  Solar power plant Koppal:
    location:
      - 15.552097
      - 76.430815
  Dell India:
    location:
      - 12.978386
      - 77.665749
    power: 0.12
  Ctrls Data Center Mumbai:
    location:
      - 19.063336
      - 72.861819
    area: 0.000465
    power: 1
