target_locations:
  Target 1:
    location:
      - 23.25991
      - 77.41261
    permanent: true
  Pavagada Solar Park:
    location:
      - 14.251944
      - 77.4475
    area: 53
    power: 2050
  Solar Power Plant Khera Silajit:
    location:
      - 25.835157
      - 79.65287
  Target 2:
    location:
      - 22.71961
      - 75.85771
    permanent: true
  Solar Power Plant Chandasar:
    location:
      - 27.972365
      - 73.063411
  Charanka Solar Park:
    location:
      - 23.9
      - 71.2
    area: 20
    power: 615
  BOSCH Solar Power Plant:
    location:
      - 15.981156
      - 74.998076
    area: 0.364
    power: 115
  Indira Paryavaran Bhawan:
    location:
      - 28.585154
      - 77.218347
    area: 0.0046
    power: 0.93
  Adani Green Energy Tamilnadu Limited:
    location:
      - 9.332771
      - 78.388731
  Ctrls Data Center Mumbai:
    location:
      - 19.063336
      - 72.861819
    area: 0.000465
    power: 1
