target_locations:
  Target 1:
    location:
      - 23.25991
      - 77.41261
    permanent: true
  Target 2:
    location:
      - 22.71961
      - 75.85771
    permanent: true
  Solar Power Plant Chandasar:
    location:
      - 27.972365
      - 73.063411
  Charanka Solar Park:
    location:
      - 23.9
      - 71.2
    area: 20
    power: 615
  Rewa Ultra Mega Solar:
    location:
      - 24.480278
      - 81.574444
    area: 6.4
    power: 750
  Indira Paryavaran Bhawan:
    location:
      - 28.585154
      - 77.218347
    area: 0.0046
    power: 0.93
  Chennai Metropolitan Area:
    location:
      - 13.083667
      - 80.268667
  Adani Green Energy Tamilnadu Limited:
    location:
      - 9.332771
      - 78.388731
  Solar power plant Koppal:
    location:
      - 15.552097
      - 76.430815
  Ctrls Data Center Mumbai:
    location:
      - 19.063336
      - 72.861819
    area: 0.000465
    power: 1
